// Service Components
// export { default as storage } from '../../services/storage.js' // removed legacy shim reference
export { default as PreferencesService } from './PreferencesService.js'
export { default as ProjectManagementService } from './ProjectManagementService.js'
//export { fsHandles } from '../../services/fsHandles.js'
export { default as AutoSync } from './AutoSync.js'
export { default as ProfileService } from './ProfileService.js'
export { default as StorageService } from './StorageService.js'
export { default as AliasModalService } from './AliasModalService.js'
export { default as CommandLibraryService } from './CommandLibraryService.js'
export { default as CommandService } from './CommandService.js'
export { default as EventHandlerService } from './EventHandlerService.js'
export { default as InterfaceModeService } from './InterfaceModeService.js'
export { default as SyncService } from './SyncService.js'
export { default as FileSystemService } from './FileSystemService.js' 