// Test to verify Activity Tracking metadata handling in ImportService
// Tests that stabilization metadata is correctly set based on TrayExec-generating activities (13, 26, 95)
import { describe, it, expect, beforeEach, afterEach, vi } from 'vitest'
import ImportService from '../../../src/js/components/services/ImportService.js'
import { createServiceFixture } from '../../fixtures/index.js'
import { respond } from '../../../src/js/core/requestResponse.js'

// Register a lightweight responder for parser operations
respond(undefined, 'parser:parse-command-string', ({ commandString }) => {
  return {
    commands: [{ command: commandString }]
  }
})

describe('ImportService - Activity Tracking Metadata Handling', () => {
  let fixture, importService

  beforeEach(() => {
    fixture = createServiceFixture()
    importService = new ImportService({
      eventBus: fixture.eventBus,
      storage: fixture.storage
    })
    importService.init()

    // Register responder for parser on the fixture event bus
    respond(fixture.eventBus, 'parser:parse-command-string', ({ commandString }) => ({ commands: [{ command: commandString }] }))
  })

  afterEach(() => {
    importService.destroy()
    fixture.destroy()
  })
 
  describe('Activity Tracking metadata handling', () => {
    it('should set stabilization metadata for keys with Activity 13 (TrayExecByTray)', async () => {
      // Mock KBF parser result with activity that generates TrayExec commands
      const mockKBFResult = {
        bindsets: {
          'TestBindset': {
            keys: {
              'F1': {
                commands: ['+TrayExecByTray 2 5'], // Generated by Activity 13
                metadata: {
                  stabilizeExecutionOrder: true // Set by activity tracking
                }
              }
            },
            metadata: {}
          }
        },
        aliases: {},
        errors: [],
        warnings: [],
        stats: {
          totalBindsets: 1,
          totalKeys: 1,
          totalAliases: 0
        }
      }

      // Mock the KBF parser
      importService.kbfParser = {
        decoder: {
          validateFormat: vi.fn().mockReturnValue({
            isValid: true,
            isKBF: true,
          })
        },
        parseFile: vi.fn().mockResolvedValue(mockKBFResult)
      }

      // Mock storage to return a test profile
      fixture.storage.getProfile = vi.fn().mockReturnValue({
        builds: {
          space: { keys: {}, aliases: {} },
          ground: { keys: {}, aliases: {} }
        },
        bindsets: {},
        aliases: {},
        keybindMetadata: {},
        bindsetMetadata: {}
      })

      const mockContent = 'mock kbf content'
      const profileId = 'test-profile'
      const environment = 'space'

      const result = await importService.importKBFFile(mockContent, profileId, environment)

      expect(result.success).toBe(true)

      // Verify that stabilizeExecutionOrder metadata was set based on Activity 13
      const savedProfile = fixture.storage.saveProfile.mock.calls[0][1]

      expect(savedProfile.bindsetMetadata.TestBindset.space.F1).toMatchObject({
        stabilizeExecutionOrder: true
      })

          })

    it('should set stabilization metadata for keys with Activity 26', async () => {
      // Mock KBF parser result with full tray execution activity
      const mockKBFResult = {
        bindsets: {
          'TestBindset': {
            keys: {
              'F1': {
                commands: [
                  '+TrayExecByTray 1 0', '+TrayExecByTray 1 1', '+TrayExecByTray 1 2',
                  '+TrayExecByTray 1 3', '+TrayExecByTray 1 4', '+TrayExecByTray 1 5',
                  '+TrayExecByTray 1 6', '+TrayExecByTray 1 7', '+TrayExecByTray 1 8', '+TrayExecByTray 1 9'
                ], // Generated by Activity 26
                metadata: {
                  stabilizeExecutionOrder: true // Set by activity tracking
                }
              }
            },
            metadata: {}
          }
        },
        aliases: {},
        errors: [],
        warnings: [],
        stats: {
          totalBindsets: 1,
          totalKeys: 1,
          totalAliases: 0
        }
      }

      // Mock the KBF parser
      importService.kbfParser = {
        decoder: {
          validateFormat: vi.fn().mockReturnValue({
            isValid: true,
            isKBF: true,
          })
        },
        parseFile: vi.fn().mockResolvedValue(mockKBFResult)
      }

      // Mock storage to return a test profile
      fixture.storage.getProfile = vi.fn().mockReturnValue({
        builds: {
          space: { keys: {}, aliases: {} },
          ground: { keys: {}, aliases: {} }
        },
        bindsets: {},
        aliases: {},
        keybindMetadata: {},
        bindsetMetadata: {}
      })

      const mockContent = 'mock kbf content'
      const profileId = 'test-profile'
      const environment = 'space'

      const result = await importService.importKBFFile(mockContent, profileId, environment)

      expect(result.success).toBe(true)

      // Verify that stabilizeExecutionOrder metadata was set based on Activity 26
      const savedProfile = fixture.storage.saveProfile.mock.calls[0][1]
      expect(savedProfile.bindsetMetadata.TestBindset.space.F1).toMatchObject({
        stabilizeExecutionOrder: true
      })

          })

    it('should set stabilization metadata for keys with Activity 95', async () => {
      // Mock KBF parser result with partial tray execution activity
      const mockKBFResult = {
        bindsets: {
          'TestBindset': {
            keys: {
              'F1': {
                commands: ['+TrayExecByTray 2 3', '+TrayExecByTray 2 4', '+TrayExecByTray 2 5'], // Generated by Activity 95
                metadata: {
                  stabilizeExecutionOrder: true // Set by activity tracking
                }
              }
            },
            metadata: {}
          }
        },
        aliases: {},
        errors: [],
        warnings: [],
        stats: {
          totalBindsets: 1,
          totalKeys: 1,
          totalAliases: 0
        }
      }

      // Mock the KBF parser
      importService.kbfParser = {
        decoder: {
          validateFormat: vi.fn().mockReturnValue({
            isValid: true,
            isKBF: true,
          })
        },
        parseFile: vi.fn().mockResolvedValue(mockKBFResult)
      }

      // Mock storage to return a test profile
      fixture.storage.getProfile = vi.fn().mockReturnValue({
        builds: {
          space: { keys: {}, aliases: {} },
          ground: { keys: {}, aliases: {} }
        },
        bindsets: {},
        aliases: {},
        keybindMetadata: {},
        bindsetMetadata: {}
      })

      const mockContent = 'mock kbf content'
      const profileId = 'test-profile'
      const environment = 'space'

      const result = await importService.importKBFFile(mockContent, profileId, environment)

      expect(result.success).toBe(true)

      // Verify that stabilizeExecutionOrder metadata was set based on Activity 95
      const savedProfile = fixture.storage.saveProfile.mock.calls[0][1]
      expect(savedProfile.bindsetMetadata.TestBindset.space.F1).toMatchObject({
        stabilizeExecutionOrder: true
      })

          })

    it('should not set stabilization metadata for keys without TrayExec-generating activities', async () => {
      // Mock KBF parser result with non-TrayExec activities
      const mockKBFResult = {
        bindsets: {
          'TestBindset': {
            keys: {
              'F1': ['cmd1', 'cmd2'] // Simple commands, no TrayExec-generating activities
            },
            metadata: {}
          }
        },
        aliases: {},
        errors: [],
        warnings: [],
        stats: {
          totalBindsets: 1,
          totalKeys: 1,
          totalAliases: 0
        }
      }

      // Mock the KBF parser
      importService.kbfParser = {
        decoder: {
          validateFormat: vi.fn().mockReturnValue({
            isValid: true,
            isKBF: true,
          })
        },
        parseFile: vi.fn().mockResolvedValue(mockKBFResult)
      }

      // Mock storage to return a test profile
      fixture.storage.getProfile = vi.fn().mockReturnValue({
        builds: {
          space: { keys: {}, aliases: {} },
          ground: { keys: {}, aliases: {} }
        },
        bindsets: {},
        aliases: {},
        keybindMetadata: {},
        bindsetMetadata: {}
      })

      const mockContent = 'mock kbf content'
      const profileId = 'test-profile'
      const environment = 'space'

      const result = await importService.importKBFFile(mockContent, profileId, environment)

      expect(result.success).toBe(true)

      // Verify that no stabilization metadata was set for non-TrayExec activities
      const savedProfile = fixture.storage.saveProfile.mock.calls[0][1]
      expect(savedProfile.keybindMetadata.space || {}).toEqual({})

    })
  })
})
